name: 'Go Mod Check Action'
description: 'Check if go.mod and go.sum are properly updated and optionally prevent indirect dependency updates'
inputs:
  prohibitIndirectDepUpdate:
    description: 'If true, the action will prohibit indirect dependency updates'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: 'Install Go'
      uses: actions/setup-go@v4
      with:
        go-version: '^1.20'
    - name: 'Run Go Mod tidy'
      run: cd $GITHUB_ACTION_PATH && go mod tidy
      shell: bash
    - name: 'Run Go Mod Check Action'
      run: go run $GITHUB_ACTION_PATH/main.go
      shell: bash
      env:
        PROHIBIT_INDIRECT_DEP_UPDATE: ${{ inputs.prohibitIndirectDepUpdate }}
