name: 'Go Mod Check Action'
description: 'Check if go.mod and go.sum are properly updated and optionally prevent indirect dependency updates'
inputs:
  prohibitIndirectDepUpdate:
    description: 'If true, the action will prohibit indirect dependency updates'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: 'Download binary'
      run: wget -q https://github.com/shoothzj/go-mod-check-action/releases/download/latest/go-mod-check; chmod +x go-mod-check
      shell: bash
    - name: 'Run Go Mod Check'
      run: ./go-mod-check
      shell: bash
      env:
        PROHIBIT_INDIRECT_DEP_UPDATE: ${{ inputs.prohibitIndirectDepUpdate }}
