name: go mod check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go_mod_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: build go mod check
        run: go build .
      - name: run go mod check
        run: export PROHIBIT_INDIRECT_DEP_UPDATE=true;./go-mod-check-action
