name: Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: Build binary
        run: go build -o go-mod-check
      - name: Release
        uses: shoothzj/latest-release-action@v1
        with:
          files: go-mod-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
